//
//  PalaceSceneView.swift
//  MemDoping
//
//  Loads the real 3D memory palace (palace_home.usdz, generated by
//  tools/blender/memory_palace.py) and shows it on a transparent background.
//  The model's nodes are named Station_0N_<Name> / Marker_0N_<Name>, matching
//  the `home` loci route order — so we can focus a stop and drop an item's emoji
//  at its marker. Real 3D is used here because loci is a spatial technique
//  (V2 FAZ3: "the strongest 3D candidate is loci").
//

import SwiftUI
import SceneKit
#if canImport(UIKit)
import UIKit
#endif

struct PalaceSceneView: View {
    /// 1-based station to focus (matches route stop order); nil = overview.
    var focusStation: Int? = nil
    /// Emoji to place at the focused station's marker (e.g. the item left there).
    var placedEmoji: String? = nil
    /// Let the player orbit the palace with a finger.
    var interactive: Bool = true

    var body: some View {
        PalaceContainer(focus: focusStation, emoji: placedEmoji, interactive: interactive)
            .accessibilityHidden(true)
    }
}

// MARK: - Scene building

private enum Palace {
    /// Loaded once and reused.
    static let template: SCNScene? = {
        guard let url = Bundle.main.url(forResource: "palace_home", withExtension: "usdz")
                ?? Bundle.main.url(forResource: "palace_home", withExtension: "usda")
        else { return nil }
        return try? SCNScene(url: url, options: nil)
    }()

    static func makeScene(focus: Int?, emoji: String?) -> SCNScene {
        let scene = SCNScene()
        scene.background.contents = nil   // transparent

        if let src = template?.rootNode.clone() {
            src.name = "palace"
            scene.rootNode.addChildNode(src)
            placeEmoji(emoji, atStation: focus, in: src)
        }

        // Lighting (the exported model may not carry lights).
        let key = SCNNode(); key.light = SCNLight(); key.light?.type = .directional
        key.light?.intensity = 900; key.eulerAngles = SCNVector3(-0.9, -0.6, 0)
        scene.rootNode.addChildNode(key)
        let amb = SCNNode(); amb.light = SCNLight(); amb.light?.type = .ambient
        amb.light?.intensity = 480; amb.light?.color = cg(0.8, 0.82, 0.9)
        scene.rootNode.addChildNode(amb)

        // Camera framing the model (or the focused station).
        let cam = SCNNode(); cam.camera = SCNCamera()
        cam.camera?.fieldOfView = 55
        cam.camera?.zNear = 0.05
        // Auto-frame from the model's bounds so it fits regardless of its scale.
        var center = SCNVector3(0, 0, 0)
        var span: Float = 6
        if let src = scene.rootNode.childNode(withName: "palace", recursively: false) {
            let (bmin, bmax) = src.boundingBox
            let local = SCNVector3((bmin.x + bmax.x) / 2, (bmin.y + bmax.y) / 2, (bmin.z + bmax.z) / 2)
            center = src.convertPosition(local, to: nil)
            span = max(bmax.x - bmin.x, max(bmax.y - bmin.y, bmax.z - bmin.z)) * Float(max(src.scale.x, 0.001))
        }
        // The exported palace is Z-up (floor on XY, height on Z), so we frame with
        // Z as the world up vector — otherwise the room comes out rolled.
        let up = SCNVector3(0, 0, 1)
        if let n = focus, let st = stationNode(n, in: scene.rootNode) {
            let t = st.worldPosition
            let d = span * 0.30
            // Stand in front of the stop (−y) and a little above it (+z).
            cam.position = SCNVector3(t.x + d * 0.5, t.y - d, t.z + d * 0.6)
            cam.look(at: t, up: up, localFront: SCNNode.localFront)
        } else {
            let d = span * 0.75
            cam.position = SCNVector3(center.x, center.y - d, center.z + d * 0.7)
            cam.look(at: center, up: up, localFront: SCNNode.localFront)
        }
        scene.rootNode.addChildNode(cam)
        return scene
    }

    private static func stationNode(_ n: Int, in root: SCNNode) -> SCNNode? {
        let key = String(format: "Station_%02d", n)
        return root.childNode(withName: key, recursively: true)
            ?? root.childNodes(passingTest: { node, _ in node.name?.hasPrefix(key) ?? false }).first
    }
    private static func markerNode(_ n: Int, in root: SCNNode) -> SCNNode? {
        let key = String(format: "Marker_%02d", n)
        return root.childNodes(passingTest: { node, _ in node.name?.hasPrefix(key) ?? false }).first
    }

    private static func placeEmoji(_ emoji: String?, atStation n: Int?, in root: SCNNode) {
        // Anchor on the station itself (the stop the camera focuses on) so the
        // dropped item is always in view; raise it on Z (the model's up axis).
        guard let emoji, let n, let anchor = stationNode(n, in: root) ?? markerNode(n, in: root),
              let image = emojiImage(emoji) else { return }
        let plane = SCNPlane(width: 1.4, height: 1.4)
        let m = SCNMaterial(); m.diffuse.contents = image; m.isDoubleSided = true; m.lightingModel = .constant
        plane.materials = [m]
        let node = SCNNode(geometry: plane)
        node.constraints = [SCNBillboardConstraint()]   // always face camera
        let p = anchor.worldPosition
        node.position = SCNVector3(p.x, p.y, p.z + 0.9)
        root.addChildNode(node)
    }

    private static func emojiImage(_ s: String) -> Any? {
        #if canImport(UIKit)
        let side: CGFloat = 128
        return UIGraphicsImageRenderer(size: CGSize(width: side, height: side)).image { _ in
            let p = NSMutableParagraphStyle(); p.alignment = .center
            let f = UIFont.systemFont(ofSize: side * 0.8)
            (s as NSString).draw(in: CGRect(x: 0, y: side * 0.08, width: side, height: side),
                                 withAttributes: [.font: f, .paragraphStyle: p])
        }
        #else
        return nil
        #endif
    }

    private static func cg(_ r: CGFloat, _ g: CGFloat, _ b: CGFloat) -> CGColor {
        CGColor(srgbRed: r, green: g, blue: b, alpha: 1)
    }
}

#if canImport(UIKit)
private struct PalaceContainer: UIViewRepresentable {
    let focus: Int?; let emoji: String?; let interactive: Bool

    /// Caches the last-built scene inputs so we only rebuild the SceneKit scene
    /// when focus/emoji actually change — not on every SwiftUI update (e.g. the
    /// per-frame drag in the place phase).
    final class Coordinator { var signature = "" }
    func makeCoordinator() -> Coordinator { Coordinator() }

    private var signature: String { "\(focus ?? -1)|\(emoji ?? "")" }

    func makeUIView(context: Context) -> SCNView {
        let v = SCNView()
        v.backgroundColor = .clear
        v.isOpaque = false
        v.antialiasingMode = .multisampling4X
        v.allowsCameraControl = interactive
        v.scene = Palace.makeScene(focus: focus, emoji: emoji)
        context.coordinator.signature = signature
        return v
    }
    func updateUIView(_ v: SCNView, context: Context) {
        v.allowsCameraControl = interactive
        if context.coordinator.signature != signature {
            context.coordinator.signature = signature
            v.scene = Palace.makeScene(focus: focus, emoji: emoji)
        }
    }
}
#else
private struct PalaceContainer: NSViewRepresentable {
    let focus: Int?; let emoji: String?; let interactive: Bool
    func makeNSView(context: Context) -> SCNView {
        let v = SCNView(); v.backgroundColor = .clear; v.allowsCameraControl = interactive
        v.scene = Palace.makeScene(focus: focus, emoji: emoji); return v
    }
    func updateNSView(_ v: SCNView, context: Context) { v.scene = Palace.makeScene(focus: focus, emoji: emoji) }
}
#endif
